language: python
python:
    - "3.5"
    - "3.6"
    - "3.7"

before_install:
    - echo $USER
    - sudo apt-get install -y environment-modules tcl python3-sphinx
    # Some tests require that the test running user belong to multiple groups.
    - sudo groupadd group_foo
    - sudo groupadd group_bar
    - sudo usermod -a -G group_foo,group_bar travis

install:
    - pip install -r requirements.txt sphinx pylint
    - ln -s pavilion.yaml.travis-ci test/data/pav_config_dir/pavilion.yaml

script: 
    - sudo -E su $USER -c "./test/run_tests -o spec_perms"
